ALTER TABLE "SplitJob" ADD COLUMN IF NOT EXISTS "isPublic" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "SplitJob" ADD COLUMN IF NOT EXISTS "priceInCents" INTEGER DEFAULT 490;
ALTER TABLE "SplitJob" ADD COLUMN IF NOT EXISTS "purchasedFrom" TEXT;
